model:
  type: "embedding"
  num_classes: 422
  encoder: "all-MiniLM-L6-v2"  # Fast, 384-dim embeddings
  classifier: "logistic_regression"

classifier_params:
  max_iter: 2000  # More iterations for 422 classes
  C: 0.5  # Slightly stronger regularization
  class_weight: "balanced"

embedding:
  batch_size: 32
  cache_embeddings: true

data:
  train_path: "data/train_combined.csv"
  valid_path: "data/valid_combined.csv"
  text_column: "caption"
  label_column: "subcategory_id"

training:
  checkpoint_path: "models/model_fine_embedding.pkl"

inference:
  confidence_threshold: 0.60

