model:
  num_classes: 422
  namespace: "t"
  
vw:
  bits: 27                    # 128M features for fine-grained classification
  learning_rate: 0.1          # Very conservative for 422 classes
  l2: 1.0e-6                  # Stronger regularization
  ngram: 3                    # Trigrams for more context
  loss_function: "logistic"
  probabilities: true

data:
  train_path: "data/train_combined.csv"
  valid_path: "data/valid_combined.csv"
  text_column: "caption"
  label_column: "subcategory_id"

training:
  log_every: 5000
  checkpoint_path: "models/model_fine_improved.vwbin"
  save_labels: false

inference:
  confidence_threshold: 0.70

