model:
  type: "embedding"
  num_classes: 422
  encoder: "BAAI/bge-large-en-v1.5"  # Same encoder for consistency
  classifier: "svm"  # Best classifier

classifier_params:
  C: 0.5  # Stronger regularization for 422 classes
  max_iter: 3000
  class_weight: "balanced"

embedding:
  batch_size: 32
  cache_embeddings: true

data:
  train_path: "data/train_combined.csv"
  valid_path: "data/valid_combined.csv"
  text_column: "caption"
  label_column: "subcategory_id"

training:
  checkpoint_path: "models/model_fine.pkl"

inference:
  confidence_threshold: 0.60
