model:
  num_classes: 45
  namespace: t
vw:
  bits: 26
  learning_rate: 0.5
  l2: 1.0e-06
  ngram: 2
  loss_function: logistic
  probabilities: true
data:
  train_path: data/train_combined.csv
  valid_path: data/valid_combined.csv
  text_column: caption
  label_column: category_id
training:
  log_every: 5000
  checkpoint_path: models/model_coarse_best.vwbin
  save_labels: false
inference:
  confidence_threshold: 0.85
