model:
  type: "embedding"
  num_classes: 45
  encoder: "BAAI/bge-large-en-v1.5"  # Best performing: 60.35% accuracy
  classifier: "svm"  # Best classifier for this task

classifier_params:
  C: 1.0
  max_iter: 2000
  class_weight: "balanced"

embedding:
  batch_size: 32
  cache_embeddings: true

data:
  train_path: "data/train_combined.csv"
  valid_path: "data/valid_combined.csv"
  text_column: "caption"
  label_column: "category_id"

training:
  checkpoint_path: "models/model_coarse.pkl"

inference:
  confidence_threshold: 0.70
